In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_excel("C:\\BaiduNetdiskDownload\\pyfile\\data.xlsx",sheet_name="data",header=0)

In [3]:
df.iloc[0:89,0:6].head(5),df.iloc[0:92,0:6].tail(5)

x1 = df.iloc[0:1,0:6]
xx1 = df.iloc[0,0:6]
#x0 = pd.concat([pd.Series([0]),x1.iloc[0,0:4]])
#x2 = pd.concat([x1.iloc[0,1:],pd.Series([0])])
#x3 = pd.concat([x1.iloc[0,2:],pd.Series([0,0])])
x00 = pd.concat([pd.Series([0]),pd.Series([0]),x1.iloc[0,0:4]])
x0 = pd.concat([pd.Series([0]),x1.iloc[0,0:5]])
x2 = pd.concat([x1.iloc[0,1:],pd.Series([0])])
x3 = pd.concat([x1.iloc[0,2:],pd.Series([0,0])])
x4 = pd.concat([x1.iloc[0,3:],pd.Series([0,0,0])])
#print(x3)
#base = pd.DataFrame([x0.values,xx1.values,x2.values,x3.values])
#base = pd.DataFrame([x00.values,x0.values,x1.values,x2.values])
base = pd.DataFrame([x00.values,x0.values,xx1.values,x2.values,x3.values,x4.values])
print(base)
matrixline1234 = base.values.reshape((1,36),order='C')
#print(matrixline1234)
ml1234=matrixline1234.tolist()
frame = pd.DataFrame([ml1234[0]])
print(frame)

    0   1   2   3   4   5
0   0   0   2   8  11  23
1   0   2   8  11  23  32
2   2   8  11  23  32  33
3   8  11  23  32  33   0
4  11  23  32  33   0   0
5  23  32  33   0   0   0
   0   1   2   3   4   5   6   7   8   9  ...  26  27  28  29  30  31  32  33  \
0   0   0   2   8  11  23   0   2   8  11 ...  32  33   0   0  23  32  33   0   

   34  35  
0   0   0  

[1 rows x 36 columns]


In [4]:
#for itr in range(1,84):
for iii in range(1,84):
    source = df.iloc[89-(iii+2):89-iii,0:6]
    #source = df.iloc[86:88,0:6]
    #source = df.iloc[87:89,0:6]
    print(source.values[1])

    sourcenow = [source.values[1],source.values[1],source.values[1],source.values[1],source.values[1],source.values[1]]
    #print(sourcenow)
    sourcelast = [source.values[0],source.values[0],source.values[0],source.values[0],source.values[0],source.values[0]]
    #print(sourcelast)
    sourceall = np.concatenate((sourcenow,sourcelast),axis=0)
    sourceallx=sourceall.reshape(2,36)
    print(sourceallx)
    
    #ilist=i for (i,x) in enumerate(matrixline1234) if (i,x) in enumerate(sourceallx[0])
    ilist=[i for i,x in enumerate(ml1234[0]) if (i,x) in enumerate(sourceallx[0])]
    #print(ilist)
    result  = sourceallx[1,ilist]
    #print(result,result)
    s  = sourceallx[0,ilist]

    rrr = pd.DataFrame([s,result])

###暂时用
    ooo = np.array([np.ceil(i/6).T for i in ilist])
    nnn = np.array([89-(iii+2)]*len(ilist))
    mmm = pd.DataFrame([s,ooo,result,nnn.T])
    if rrr.shape[1]:
        frame = frame.append(mmm.T)
    

[3 7 8 15 29 30]
[[3 7 8 15 29 30 3 7 8 15 29 30 3 7 8 15 29 30 3 7 8 15 29 30 3 7 8 15 29
  30 3 7 8 15 29 30]
 [2 5 9 15 20 24 2 5 9 15 20 24 2 5 9 15 20 24 2 5 9 15 20 24 2 5 9 15 20
  24 2 5 9 15 20 24]]
[2 5 9 15 20 24]
[[2 5 9 15 20 24 2 5 9 15 20 24 2 5 9 15 20 24 2 5 9 15 20 24 2 5 9 15 20
  24 2 5 9 15 20 24]
 [3 10 14 17 18 30 3 10 14 17 18 30 3 10 14 17 18 30 3 10 14 17 18 30 3
  10 14 17 18 30 3 10 14 17 18 30]]
[3 10 14 17 18 30]
[[3 10 14 17 18 30 3 10 14 17 18 30 3 10 14 17 18 30 3 10 14 17 18 30 3
  10 14 17 18 30 3 10 14 17 18 30]
 [14 15 17 22 24 29 14 15 17 22 24 29 14 15 17 22 24 29 14 15 17 22 24 29
  14 15 17 22 24 29 14 15 17 22 24 29]]
[14 15 17 22 24 29]
[[14 15 17 22 24 29 14 15 17 22 24 29 14 15 17 22 24 29 14 15 17 22 24 29
  14 15 17 22 24 29 14 15 17 22 24 29]
 [4 7 13 20 29 33 4 7 13 20 29 33 4 7 13 20 29 33 4 7 13 20 29 33 4 7 13
  20 29 33 4 7 13 20 29 33]]
[4 7 13 20 29 33]
[[4 7 13 20 29 33 4 7 13 20 29 33 4 7 13 20 29 33 4 7 13 20 29 33 4 7 13
  20 2

[4 6 15 28 32 33]
[[4 6 15 28 32 33 4 6 15 28 32 33 4 6 15 28 32 33 4 6 15 28 32 33 4 6 15
  28 32 33 4 6 15 28 32 33]
 [8 13 17 18 20 27 8 13 17 18 20 27 8 13 17 18 20 27 8 13 17 18 20 27 8
  13 17 18 20 27 8 13 17 18 20 27]]
[8 13 17 18 20 27]
[[8 13 17 18 20 27 8 13 17 18 20 27 8 13 17 18 20 27 8 13 17 18 20 27 8
  13 17 18 20 27 8 13 17 18 20 27]
 [3 9 13 22 23 25 3 9 13 22 23 25 3 9 13 22 23 25 3 9 13 22 23 25 3 9 13
  22 23 25 3 9 13 22 23 25]]
[3 9 13 22 23 25]
[[3 9 13 22 23 25 3 9 13 22 23 25 3 9 13 22 23 25 3 9 13 22 23 25 3 9 13
  22 23 25 3 9 13 22 23 25]
 [2 10 11 17 18 29 2 10 11 17 18 29 2 10 11 17 18 29 2 10 11 17 18 29 2
  10 11 17 18 29 2 10 11 17 18 29]]
[2 10 11 17 18 29]
[[2 10 11 17 18 29 2 10 11 17 18 29 2 10 11 17 18 29 2 10 11 17 18 29 2
  10 11 17 18 29 2 10 11 17 18 29]
 [3 15 17 23 27 30 3 15 17 23 27 30 3 15 17 23 27 30 3 15 17 23 27 30 3
  15 17 23 27 30 3 15 17 23 27 30]]
[3 15 17 23 27 30]
[[3 15 17 23 27 30 3 15 17 23 27 30 3 15 17 23 27 30 3 15 17 23 2

In [5]:
s

array([32], dtype=object)

In [6]:
print(frame)
frame.to_excel(excel_writer="C:\\BaiduNetdiskDownload\\pyfile\\datao.xlsx",sheet_name="Sheet1")

      0    1     2     3     4     5    6    7    8     9  ...     26    27  \
0    0.0  0.0   2.0   8.0  11.0  23.0  0.0  2.0  8.0  11.0 ...   32.0  33.0   
0    8.0  2.0   9.0  86.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0    2.0  2.0   3.0  85.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0   33.0  3.0  26.0  82.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0    2.0  2.0  12.0  81.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0   32.0  3.0  22.0  79.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
1   33.0  3.0  24.0  79.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0    8.0  2.0  25.0  78.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0   33.0  3.0  26.0  77.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0   23.0  2.0  18.0  76.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
1    2.0  2.0   1.0  76.0   NaN   NaN  NaN  NaN  NaN   NaN ...    NaN   NaN   
0   32.0  2.0  27.0  74.0   NaN   NaN  NaN  NaN  NaN